#set up properties
PROJECT_ID: consultasbigquery

server:
 port: ${DEFAULT_PORT:8080}

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/consult_bd
        username: root
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true

    application:
        name: app-bigquery
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, bigquery
            label: master
        gcp:
            project-id: ${PROJECT_ID:consultasbigquery}
            credentials:
                location: classpath:consultasbigquery-40f42a847fca.json
            bigquery:
                datasetName: ${DATASET_NAME:bigquery-public-data}